force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <description>Responsavel por prover garantia de entrega para camada de integração</description>
    <label>Event Queue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QueueCode</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>Event Name or Transaction Name</description>
    <label>Event Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>PROCESSING</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
            <value>
                <fullName>BATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventQueueTriggerHandler.cls
/**
 * Created by marcelo.cost on 22/2/2022.
 */

public with sharing class EventQueueTriggerHandler {
    public EventQueueTriggerHandler() {

        //all elements with status__c = Queued
        Map<String, String> events = new Map<String, String>();

        Integer i = 0;

        if (System.isBatch() || System.isFuture()) {
            System.debug('Dequeue is in future method. Ignore');
            return;
        }

        for (Queue__c event : (List<Queue__c>)trigger.new) {

            if (event.status__c != EventQueueStatusType.QUEUED.name()) {
                continue;
            }

// Callout Control, only 100 simultaneous.
            if (i == EventExecutor.FUTURE_CALL_SIZE) {
                EventExecutor.processEvents(events);
                events = new Map<String, String>();
                i = 0;
            }

            events.put(event.id, event.eventName__c);
            i++;
        }

        if (events.size() > 0) {
            System.debug('DeQueueProcessor - Process last batch ' + events.size());
            EventExecutor.processEvents(events);
        }
    }
}