demo/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

demo/main/default/objects/Book__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BookTransformer.cls
/**
 * @author: Heitor Araujo on 12/10/2017.
 */

public with sharing class BookTransformer {

    public Book__c transformFromVO(Book bookVO){

        Book__c book = new Book__c();

        book.Name = bookVO.name;
        book.Author__c = bookVO.author;
        book.ReleaseDate__c = bookVO.releaseDate;
        book.ExternalId__c = bookVO.externalId; 
        book.Id = bookVO.id;

        return book;
    }

    public Book transformToVO(Book__c book){

        Book bookVO = new Book();

        bookVO.id = book.Id;
        bookVO.name = book.Name;
        bookVO.author = book.Author__c;
        bookVO.releaseDate = book.ReleaseDate__c;

        return bookVO;
    }
}